# Generated by Django 4.2.4 on 2025-01-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed_test', '0002_customword'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingtest',
            name='mistakes',
            field=models.JSONField(default=list),
        ),
    ]
