# Generated by Django 4.2.4 on 2025-01-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed_test', '0003_typingtest_mistakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingtest',
            name='word_mistakes',
            field=models.JSONField(default=list),
        ),
    ]
